-- DROP DATABASE IF EXISTS DEAL_SETUP_POC;
CREATE DATABASE IF NOT EXISTS DEAL_SETUP_POC;

CREATE TABLE IF NOT EXISTS DEAL_SETUP_POC.DEALS(deal_id INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
client_name VARCHAR(20) NOT NULL,
deal_name VARCHAR(20) NOT NULL, 
due_date DATE NOT NULL,
priority_id VARCHAR(12) NOT NULL,
status VARCHAR(100));

CREATE TABLE IF NOT EXISTS DEAL_SETUP_POC.REVIEW_TYPE(review_id INT AUTO_INCREMENT PRIMARY KEY, 
review_type VARCHAR(50) NOT NULL);

INSERT INTO DEAL_SETUP_POC.REVIEW_TYPE(review_type) VALUES('CREDIT');
INSERT INTO DEAL_SETUP_POC.REVIEW_TYPE(review_type) VALUES('COMPLIANCE');
INSERT INTO DEAL_SETUP_POC.REVIEW_TYPE(review_type) VALUES('LOAN MOD');
INSERT INTO DEAL_SETUP_POC.REVIEW_TYPE(review_type) VALUES('SECURITIZATION');


CREATE TABLE IF NOT EXISTS DEAL_SETUP_POC.DEAL_REVIEW_TYPE (deal_review_id int(5) NOT NULL AUTO_INCREMENT, PRIMARY KEY (`deal_review_id`),
deal_id int, CONSTRAINT FK_deal_id FOREIGN KEY (deal_id) REFERENCES DEAL_SETUP_POC.DEALS (deal_id), 
review_id int, CONSTRAINT FK_review_id FOREIGN KEY (review_id) REFERENCES DEAL_SETUP_POC.REVIEW_TYPE(review_id));

CREATE TABLE IF NOT EXISTS DEAL_SETUP_POC.LOAN(
loan_id VARCHAR(20) PRIMARY KEY,
deal_id INT,
borrower_name VARCHAR(20) NOT NULL,
process_inst_id VARCHAR(20),
ssn VARCHAR(20) NOT NULL,
loan_type VARCHAR(20) NOT NULL,
loan_amount DECIMAL(10,4), CONSTRAINT foreignkey_deal_id FOREIGN KEY (deal_id) REFERENCES DEAL_SETUP_POC.DEALS(deal_id));

CREATE TABLE IF NOT EXISTS DEAL_SETUP_POC.REVIEW_TASK_TYPE(review_task_type_id INT AUTO_INCREMENT PRIMARY KEY,task_name VARCHAR(50) NOT NULL,
review_id INT, CONSTRAINT fkey_review_id FOREIGN KEY (review_id) REFERENCES DEAL_SETUP_POC.REVIEW_TYPE(review_id));

INSERT INTO DEAL_SETUP_POC.REVIEW_TASK_TYPE(task_name,review_id) VALUES('PayStub',1);
INSERT INTO DEAL_SETUP_POC.REVIEW_TASK_TYPE(task_name,review_id) VALUES('W2',1);
INSERT INTO DEAL_SETUP_POC.REVIEW_TASK_TYPE(task_name,review_id) VALUES('Credit Check',1);
INSERT INTO DEAL_SETUP_POC.REVIEW_TASK_TYPE(task_name,review_id) VALUES('Credit Card',2);
INSERT INTO DEAL_SETUP_POC.REVIEW_TASK_TYPE(task_name,review_id) VALUES('EMI',2);
INSERT INTO DEAL_SETUP_POC.REVIEW_TASK_TYPE(task_name,review_id) VALUES('Credit Check',2);
INSERT INTO DEAL_SETUP_POC.REVIEW_TASK_TYPE(task_name,review_id) VALUES('Paystub',3);
INSERT INTO DEAL_SETUP_POC.REVIEW_TASK_TYPE(task_name,review_id) VALUES('Investment',3);
INSERT INTO DEAL_SETUP_POC.REVIEW_TASK_TYPE(task_name,review_id) VALUES('Credit Check',3);
INSERT INTO DEAL_SETUP_POC.REVIEW_TASK_TYPE(task_name,review_id) VALUES('Credit Card',4);
INSERT INTO DEAL_SETUP_POC.REVIEW_TASK_TYPE(task_name,review_id) VALUES('Paystub',4);



